module.exports = [
    // 'babel-polyfill',
    // 'es6-promise',
    // 'react-dom',
    // 'react-router',
    // 'react-router-dom',
    // 'react',
    // 'axios',
    // 'accounting',
    // 'node-uuid',
    // 'path-to-regexp',
    // 'prop-types',
    // 'q',
    // 'react-click-outside',
    // 'react-modal',
    // 'react-notification-system',
    // 'react-select',
    // 'react-tooltip',
    // 'react-waypoint',
    // 'tether-drop',
    // 'jquery-datetimepicker/build/jquery.datetimepicker.full'
]
